language: cpp
compiler: gcc
dist: trusty
sudo: required

# Install newer gcc and install llvm
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install -qq libyajl-dev libxml2-dev libxqilla-dev
- if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
- sudo apt-get install llvm-3.8

before_script:
- PreviousPWD=$PWD
# Install newer CMake
- CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
- mkdir cmake
- cd cmake
- wget --no-check-certificate ${CMAKE_URL} -O cmake.tar.gz
- tar -xzf cmake.tar.gz
- export RUN_CMAKE=${PWD}/cmake-3.5.2-Linux-x86_64/bin/cmake
- cd $PreviousPWD

script:
- mkdir build
- cd build
- echo $LLVM_INSTALLATION
- ${RUN_CMAKE} .. -DENABLE_TESTING=1
- make
- make test

after_failure:
- cd Testing/Temporary
- cat CTestCostData.txt
- cat LastTest.txt
